name: "🕵️‍♂️ Checking compliance"

# 1. Déclencheur permettant d'être appelé par d'autres dépôts
on:
  workflow_call:

jobs:
  # --- SCAN DE SÉCURITÉ ---
  security:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown --fail

  # --- CONFORMITÉ DE LA BRANCHE ---
  branch-check:
    name: Branch Naming Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check branch format
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          REGEXP='^(feat|fix|docs|infra|chore)\/[0-9]+-[a-z0-9-]+$'
          if [[ ! $BRANCH_NAME =~ $REGEXP ]]; then
            echo "❌ Erreur : '$BRANCH_NAME' ne respecte pas le référentiel 002."
            exit 1
          fi

  # --- CONFORMITÉ DES COMMITS ---
  commit-lint:
    name: Commitlint Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint commits
        uses: wagoid/commitlint-github-action@v6